name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - .github/workflows/doc.yml
      - keymap-drawer/keymap_drawer.config.yaml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      config_path: keymap-drawer/keymap_drawer.config.yaml
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
